name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.6.5
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - jupyterlab
  - ipython
  - clang_osx-64
  - gcc_linux-64
  # Put any conda dependencies here

  - pip:
    # Put any pip dependencies here (and no conda ones anywhere below)

  # Tooling requirements (don't edit)
    - tornado>=5.0  # Required to stop luigi from breaking jupyter
    - tqdm
    - pyyaml
    - tables
    - black
    - blackcellmagic
    - pymysql
    - sqlalchemy
    - click
    - Sphinx
    - sphinxcontrib.napoleon
    - coverage
    - awscli
    - flake8
  - python-dotenv>=0.5.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jq
  - pytest
