site_name: Cookiecutter Data Science @ Nesta
site_description: A project template and directory structure for Nesta Python data science projects.
site_favicon: favicon.ico
repo_url: https://github.com/nestauk/cookiecutter-data-science-nesta
edit_uri: edit/master/docs/docs
copyright: 
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: docs/index.md
